# This is a basic workflow to help you get started with Actions

name: MainDevelopmentPipeline

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      MANUAL_COMMIT_ID:
        description: Mnaul commit MANUAL_COMMIT_ID
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in paralle

jobs:
  runtestscripts:
    runs-on: ubuntu-latest
    # Check install
    steps:
    
    # Steps represent a sequence of tasks that will be executed as part of the job
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it    
    
      - uses: actions/checkout@v2
         
      - name: Install Salesforce CLI in ubuntu
        run: |
           wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
           mkdir sfdx-cli
           tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
           ./sfdx-cli/install
           export PATH=~/sfdx/bin:$PATH           
           sfdx --version
           echo "hello world"
           sfdx force:config:set defaultusername=test-2mmvrtm5q2ay@example.com
           echo ${SALESFORCE_CONSUMER_KEY} > server.key     
           sfdx auth:jwt:grant --clientid 3MVG9e2mBbZnmM6mhRc4FSSF1DZEpqOwQFiqShNuG.pAABT136EBalqJant7fGWzehyqwFIgMmav0.PdlvGCQ --username test-2mmvrtm5q2ay@example.com --jwtkeyfile server.key --setdefaultdevhubusername -a SalesforceScratchOrg --instanceurl https://test.salesforce.com 
       #    sfdx auth:jwt:grant --clientid ${{ secrets.CONSUMER_KEY }} --username ${{ secrets.USERNAME }} --jwtkeyfile server.key --setdefaultdevhubusername -a SalesforceScratchOrg --instanceurl ${{ secrets.INSTANCE_URL }}
        env:
           SALESFORCE_CONSUMER_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}
