# This is a basic workflow to help you get started with Actions

name: MainDevelopmentPipeline

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      MANUAL_COMMIT_ID:
        description: Mnaul commit MANUAL_COMMIT_ID
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in paralle

jobs:
  runtestscripts:
    runs-on: ubuntu-latest
    # Check install
    steps:
    
    # Steps represent a sequence of tasks that will be executed as part of the job
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it    
    
      - uses: actions/checkout@v2
         
      - name: Install Salesforce CLI in ubuntu
        run: |
           wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
           mkdir sfdx-cli
           tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
           ./sfdx-cli/install
           sfdx --version
           echo "authicatting to scratch org"
           echo "${SALESFORCE_CONSUMER_KEY}" > server.key     
           sfdx auth:jwt:grant --clientid ${{ secrets.CONSUMER_KEY }} --username ${{ secrets.USERNAME }} --jwtkeyfile server.key --setdefaultdevhubusername -a SalesforceScratchOrg --instanceurl ${{ secrets.INSTANCE_URL }}
           cat testclasses | tr ',' '\n' | while read word; do
               echo $word
           done
           value=`cat testclasses`
           echo "$value"
           ls -ltr
           declare -a arr
           arr=(helloworld,helloworld2,helloworld3,helloworld4)
           echo ${arr[@]}
           echo "${arr[@]}"
           sfdx force:source:deploy -c -p force-app -u SalesforceScratchOrg
           sfdx force:source:deploy -c -p force-app -l RunSpecifiedTests -r $value -u SalesforceScratchOrg 
     #     sfdx auth:jwt:grant --clientid 3MVG9e2mBbZnmM6mhRc4FSSF1DZEpqOwQFiqShNuG.pAABT136EBalqJant7fGWzehyqwFIgMmav0.PdlvGCQ --username test-2mmvrtm5q2ay@example.com --jwtkeyfile server.key --setdefaultdevhubusername -a SalesforceScratchOrg --instanceurl https://test.salesforce.com 
      #    echo 'y' | sfdx plugins:install sfpowerkit
      #    echo 'y' | sfdx plugins:install @dxatscale/sfpowerscripts
        env:
           SALESFORCE_CONSUMER_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}

          
