name: 'newcurlcall'

on:
  workflow_dispatch:
    inputs:
      environments:
        description: enter environments with comma separated values
        required: true
        type: string
        default: test
jobs:
  deltapkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: curl back
        run: |
          variable=${{ inputs.environments }} 
          echo branch name is $GITHUB_REF
          for i in ${variable//,/ }
          do
              # call your procedure/other scripts here below
              echo "$i"
              curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GITHUBTOKENCURL"\
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/ImRaj90/SalesforceCICD/actions/workflows/15845872/dispatches \
                 -d '{"ref":"main", "inputs": { "manual_commit_id":"Command Line User", "UAT_SANDBOX":"true","DEV_SANDBOX":"true","Name":"cschleiden","environment":"$i" }}'

          done    
        env:
          GITHUBTOKENCURL: ${{ secrets.GITHUBTOKENCURL }}
          

