name: 'newcurlcall'

on:
  workflow_dispatch:
    inputs:
      manual_commit_id:
        description: enter commit id
        required: true
        type: string      
jobs:
  deltapkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: curl back
        run: |            
              curl -L   -X POST   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer {{secrets.GITHUBTOKENCURL}}"  -H "X-GitHub-Api-Version: 2022-11-28"   https://api.github.com/repos/ImRaj90/SalesforceCICD/actions/workflows/15845872/dispatches    -d '{"ref":"main", "inputs": { "manual_commit_id":"Command Line User", "UAT_SANDBOX":"true","DEV_SANDBOX":"true","Name":"cschleiden","environment":"Test_Env6" }}'
