name: 'newcurlcall'

on:
  workflow_dispatch:
    inputs:
      manual_commit_id:
        description: enter commit id
        required: true
        type: string
        default: test
jobs:
  deltapkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: curl back
        run: |            
          chmod +x devops-scripts/curl.sh
          ./devops-scripts/curl.sh
          

