name: 'newcurlcall'

on:
  workflow_dispatch:
    inputs:
      manual_commit_id:
        description: enter commit id
        required: true
        type: string
        default: test
jobs:
  deltapkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: curl back
        run: |         
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUBTOKENCURL"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ImRaj90/SalesforceCICD/actions/workflows
        env:
          GITHUBTOKENCURL: ${{ secrets.GITHUBTOKENCURL }}
          

