name: 'prdeploy'

on:
  push:
    branches:
      - develop
      
jobs:
  deltapkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install salesforce
        run: |
          npm install -g sfdx-cli 
          echo 'y' | sfdx plugins:install sfpowerkit
          echo 'y' | sfdx plugins:install @dxatscale/sfpowerscripts          
      - name: get previous commitid & delta 
        run: |
          git_previous_commitid=$(curl -H "Authorization: $SOURCE_TOKEN" "https://api.github.com/repos/ImRaj90/SalesforceCICD/actions/workflows/deltapkg.yml/runs?status=success" | grep -i head_sha | head -1 | cut -d "," -f1 | awk -F ":" '{print $2}' | sed 's/"//g' | xargs)
          echo git_previous_commitid: $git_previous_commitid
          branchName2=`git log -1 --pretty=format:"%s" | awk '{split($0,a,":"); print a[1]}'`
          deploymentType=`git log -1 --pretty=format:"%s" | awk '{split($0,a,":"); print a[2]}'`
          SandboxName=`git log -1 --pretty=format:"%s" | awk '{split($0,a,":"); print a[4]}'`
          head1=`git rev-list -1 $branchName2`
          echo branchName2 $branchName2
          echo deploymentType $deploymentType
          echo SandboxName $SandboxName
          git_previous_branchcommitd=$(curl -H "Authorization: $SOURCE_TOKEN" "https://api.github.com/repos/ImRaj90/SalesforceCICD/actions/workflows/deltapkg.yml/runs?status=success" | grep -A1 develop | head -2 | cut -d "," -f1 | awk '{split($0,a,":"); print a[2]}' | tail -1 | xargs)
          echo $git_previous_branchcommitd
          sfdx sfpowerkit:project:diff --revisionfrom $git_previous_commitid --revisionto $head1 --output OutputFolder
          tree OutputFolder

      - name: deltapkg these
        run: |
         sfdx sfpowerkit:project:diff --revisionfrom $git_previous_commitid --revisionto $head1 --output OutputFolder
         tree OutputFolder
