name: 'prraise'

on:
  pull_request:
    types: open
    branches:
      - develop
      
jobs:
  prdetails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: prdetails base
        run: |
          echo base ${{ github.base_ref }}
      - name: prdetails source
        run: |
          echo source ${{ github.head_ref }}
