name: 'secretstest'

on: [push]
jobs:
  getsecrets:
    runs-on: ubuntu-latest
    environment: sf2406dev
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get environment variable
        run: |
          echo base ${{ secrets.SANDBOX_URL }}
