name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/workflow-B.yml
    with:
      config-path: .github/labeler.yml
      token: ${{ vars.VARIABLETEST }}
