name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      token:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: getting variables
      run: |
        echo ${{ inputs.config-path }}
        echo ${{ vars.VARIABLETEST }}


